global:
  # # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'google.com:587'
  smtp_from: 'daysacsilva@gamil.com'
  smtp_auth_username: 'daysacsilva'
  smtp_auth_password: 'senhafalsa'


# The root route on which each incoming alert enters.
route:
  receiver: Default
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

  routes:
    - receiver: Alerta Critico
      match:
        severity: high

    - receiver: Alerta Sucesso
      match:
        team: all

receivers:
  - name: Default
    email_configs:
      - to: 'daysa.silva@ibm.com'
  - name: Alerta Critico
    email_configs:
      - to: 'daysa.silva@ibm.com'
  - name: Alerta Sucesso
    email_configs:
      - to: 'daysa.silva@ibm.com'
