global:
  scrape_interval: 30s
  evaluation_interval: 15s

rule_files:
  - prometheus.rules.yaml

scrape_configs:
  - job_name: Prometheus
    static_configs:
      - targets:
        - localhost:9090

remote_write:
  - url: http://192.168.1.100:9094he/api/v1/push
    headers:
      X-Scope-OrgID: fake